### ISSUE TITLE
errors when compiling, undefined reference

### ISSUE THREAD

**Issue by alx-1** [leonyuhanov/ESP32APA102Driver#1]
Hello,

I'm getting this error when I try compiling with "idf.py build".

` "undefined reference to `initLEDs'"` followed by all your other functions. I'm using 4.0 version of the esp-idf.

ty for sharing your code.

* update : I created a component folder for the dependencies (I guess it is required for my version of the esp-idf) and it compiles and looks great! ty again. Let me know if you would like me to add the changes.
<img width="792" alt="Capture d’écran, le 2021-04-11 à 19 14 34" src="https://user-images.githubusercontent.com/2613132/114324804-42506a80-9afa-11eb-8455-e2d953d09ead.png">

**Comment by leonyuhanov** [comment]
Heya
This has something to do with the way the new SDK compiles. includes. My c foo is pretty low, ill have to re read their sdk

**Comment by leonyuhanov** [comment]
@alx-1 ok found the issue. In the latest SDK they changed the way you need to include source files. I have updated the repo. grab it all again and do a  clean

`idf.py build`

**Comment by alx-1** [comment]
Yes that's great and fast thank you. I had found a workaround by making it into a component. But this compiles without change.  Here is a quick video of my sequencer in progress :).  Out of curiosity, what was the change?  I'm adapting your code for my project but I get the same earlier error with my moving your files into the 'components' folder. I might move them out with your new code now just so it works.

https://user-images.githubusercontent.com/2613132/114332334-06c29a00-9b14-11eb-934e-0213d1aba5a4.mp4

**Comment by leonyuhanov** [comment]
In file 

`https://github.com/leonyuhanov/ESP32APA102Driver/blob/master/main/CMakeLists.txt`

You need to add each source file into this:

`set(srcs "ESP32APA102Driver.c" "apa102LEDStrip.c" "colourObject.c")`

Do the same for your project

**Comment by alx-1** [comment]
THANK YOU!  It works in my project, it's super stable and *feels* fast solved some long standing issues I had with another driver. I did make it into a component.  If you want to see it : https://github.com/alx-1/technologies-de-la-fete/wiki .  It's a project that incorporates Ableton Link so it can be in sync with audio. Right now, it sends a midi clock and notes to my Volca Beats or modular instruments.  

https://user-images.githubusercontent.com/2613132/114334971-af272d00-9b19-11eb-9510-11c0a9622ff8.mp4

**Comment by leonyuhanov** [comment]
Great to hear mate, awesome project. If your on insta stay in touch https://www.instagram.com/wow_elec_tron/ I'm betting our project ideas overlap in many areas

**Comment by alx-1** [comment]
Ah I don't have insta. I did see a few cool projects before the 'register notice' showed up. Social media fun. This is another project I did with LEDs in bicycle wheels (inspired by LadyAda) https://agitpov.org/ and https://github.com/AgitPOV/AgitPOV_WiFi. Keep in touch about your projects!

**Comment by alx-1** [comment]
Updated documentation of the project with more modules : https://www.youtube.com/watch?v=PumZxMrdcCg
Thank you again :))
